#!/usr/bin/env bash
# This script displays DNS A records for given subdomains

domain=$1
subdomain=$2

get_record() {
    sub=$1
    dom=$2

    ip=$(dig +short "${sub}.${dom}")

    echo "The subdomain ${sub} is a A record and points to ${ip}"
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02
    do
        get_record "$sub" "$domain"
    done
else
    get_record "$subdomain" "$domain"
fi