#!/usr/bin/env bash
# Script to display DNS records of subdomains

domain=$1
subdomain=$2

get_record() {
    sub=$1
    ip=$(dig +short "$sub.$domain" | awk '{print $1}')
    echo "The subdomain $sub is a A record and points to $ip"
}

if [ -z "$subdomain" ]; then
    for sub in www lb-01 web-01 web-02
    do
        get_record "$sub"
    done
else
    get_record "$subdomain"
fi